version: '3.1'
services:
  web:
    build: ./docker
    ports: ['10001:80']
    restart: always
    volumes:
        - "./:/var/www/html"
  db:
    image: mysql:5.6
    restart: always
    ports: ['10010:3306']
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: tobedone
        MYSQL_DATABASE: ssrpanel
        MYSQL_USER: ssrpanel
        MYSQL_PASSWORD: SeeThai9Iroedeehuy7shah2sie1ohfi