version: '3.1'
services:
  db:
    image: mysql:5.7
		volumes:
			- db_data:/var/lib/mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: ssrpanel
        MYSQL_USER: ssrpanel
        MYSQL_PASSWORD: ${MYSQL_PASS}
  web:
    image: ryanw4ng/web:latest
    ports: 
			- "80:80"
    depends_on: db
		environment:
			DB_HOST: db
			DB_USER: ssrpanel
      DB_PASSWORD: ${MYSQL_PASS}
  quene:
    image: ryanw4ng/web:quene
    depends_on: db
    environment:
			DB_HOST: db
			DB_USER: ssrpanel
      DB_PASSWORD: ${MYSQL_PASS}
  ssgo:
    image: ryanw4ng/ssgo
    environment: 
      
volumes:
	db_data:
